import React from 'react';
import { 
  // Base
  Zap, AlertTriangle, Info, CheckCircle, XCircle, HelpCircle, Activity, 
  Box, Camera, Flame, Crop, Anchor, Aperture, Archive, ArrowDownCircle, 
  ArrowUpCircle, AtSign, Award, BarChart, Battery, Bell, Bluetooth, 
  Book, Bookmark, Briefcase, Calendar, CameraOff, Cast, CheckSquare, 
  ChevronDown, ChevronUp, Clock, Cloud, Code, Coffee, Columns, Command, 
  Compass, Copy, Cpu, CreditCard, Crosshair, Database, Disc, DollarSign, 
  Download, Droplet, Edit, Eye, EyeOff, File, FileText, Film, Filter, 
  Flag, Folder, Gift, Globe, Grid, HardDrive, Hash, Headphones, Heart, 
  Home, Image, Inbox, Key, Layers, Layout, LifeBuoy, Link, List, Lock, 
  LogIn, LogOut, Mail, Map, MapPin, Maximize, Menu, MessageCircle, 
  MessageSquare, Mic, Minimize, Minus, Monitor, Moon, MoreHorizontal, 
  MoreVertical, MousePointer, Move, Music, Navigation, Octagon, Package, 
  Paperclip, Pause, Phone, PieChart, Play, Plus, PlusCircle, Power, 
  Printer, Radio, RefreshCcw, RefreshCw, Repeat, Save, Scissors, Search, 
  Send, Server, Settings, Share, Shield, ShoppingBag, ShoppingCart, 
  Shuffle, Sidebar, Smartphone, Smile, Speaker, Square, Star, StopCircle, 
  Sun, Table, Tablet, Tag, Target, Terminal, Thermometer, ThumbsDown, 
  ThumbsUp, ToggleLeft, ToggleRight, Wrench, Trash, Trash2, TrendingDown, 
  TrendingUp, Truck, Tv, Umbrella, Unlock, Upload, User, UserCheck, 
  UserMinus, UserPlus, UserX, Users, Video, Voicemail, Volume, Volume1, 
  Volume2, VolumeX, Watch, Wifi, WifiOff, Wind, X, ZoomIn, ZoomOut,
  
  // Interior & Construction
  Armchair, Bed, BedDouble, Lamp, Sofa, DoorOpen, DoorClosed, Refrigerator,
  Microwave, Bath, ShowerHead, ChefHat, Utensils, Construction, Ruler,
  Hammer, Drill, Plug, Plug2, Lightbulb, LightbulbOff, Fan, ThermometerSnowflake,
  ThermometerSun, Droplets, Waves, Recycle, TreePine, Leaf, Flower, Dog, Cat,
  Car, Bike, Bus, Train, Plane, ParkingCircle, Signpost, Siren, Megaphone,
  RadioTower, Signal, Router, Network, Share2, BluetoothConnected, Usb,
  Keyboard, Mouse, Laptop, Projector, Calculator, PenTool, Brush, Palette,
  Pipette, Eraser, Stamp, Wand, Crop as CropIcon, Frame, Grid3X3, 
  Minimize2, Move as MoveIcon, RotateCcw, RotateCw, ZoomIn as ZoomInIcon, ZoomOut as ZoomOutIcon,
  
  // New Additions (Expansion)
  AirVent, Accessibility, Anvil, ArrowBigDown, ArrowBigLeft, ArrowBigRight, ArrowBigUp,
  ArrowDownLeft, ArrowDownRight, ArrowUpLeft, ArrowUpRight, Axe, Backpack, Banknote,
  Baseline, Beaker, Bean, BedSingle, Beer, Bike as BikeIcon, Binary, Biohazard,
  Blinds, Blocks, BluetoothSearching, Bomb, Bone, Bot, BoxSelect, Braces, Brain,
  BrickWall, Bug, Building, Building2, Cable, Calculator as CalcIcon, CalendarCheck,
  Candy, CarFront, Carrot, Castle, Cctv, Check, CheckCheck, Cigarette, CigaretteOff,
  Circle, CircleDashed, CircleDot, CircuitBoard, Clapperboard, Clipboard, ClipboardCheck,
  CloudCog, CloudRain, CloudSnow, CloudSun, CloudLightning, Club, Code2, Coins, Combine,
  ConciergeBell, Contact, Contrast, Cookie, Copyright, CornerDownLeft, CornerDownRight,
  Cpu as CpuIcon, CreativeCommons, Croissant, Cross, Crown, CupSoda,
  Cylinder, DatabaseBackup, Diamond, Dice1, Dice2, Dice3, Dice4, Dice5, Dice6,
  Dna, DoorOpen as DoorOpenIcon, Ear, Earth, Egg, Equal, Eraser as EraserIcon,
  Euro, Expand, Factory, Feather, Fence, FileAudio, FileBadge, FileBox, FileCheck,
  FileCode, FileCog, FileDigit, FileImage, FileInput, FileJson, FileLock, FileOutput,
  FilePieChart, FileSearch, FileSpreadsheet, FileSymlink, FileTerminal, FileType,
  FileVideo, FileVolume, FileWarning, Files, Film as FilmIcon, Fingerprint, FireExtinguisher,
  Fish, FlaskConical, FlipHorizontal, FlipVertical, Flower2, FoldHorizontal, FoldVertical,
  Footprints, Forklift, FormInput, Forward, Frame as FrameIcon, Framer, Frown, Fuel,
  FunctionSquare, Gamepad, Gamepad2, Gavel, Gem, Ghost, GitBranch, GitCommit, GitMerge,
  GitPullRequest, Glasses, Goal, Grab, GraduationCap, Grape, GripHorizontal, GripVertical,
  Group, Hammer as HammerIcon, Hand, HandMetal, HardHat, Haze, Heading, Headphones as HeadphonesIcon,
  HeartCrack, HelpCircle as HelpIcon, Hexagon, Highlighter, History, Hop, Hourglass, IceCream,
  ImageMinus, ImagePlus, Import, Indent, Infinity as InfinityIcon, Inspect, Instagram, Italic, IterationCcw,
  IterationCw, Joystick, Keyboard as KeyboardIcon, LampCeiling, LampDesk, LampFloor, LampWallUp,
  Landmark, Languages, Lasso, LassoSelect, Layers as LayersIcon, LayoutDashboard, LayoutGrid,
  LayoutList, LayoutPanelLeft, LayoutPanelTop, LayoutTemplate, Library, LifeBuoy as LifeBuoyIcon,
  Lightbulb as LightbulbIcon, LineChart, Link2, Link2Off, Linkedin, ListChecks, ListMusic,
  ListPlus, ListVideo, Loader, Loader2, Locate, LocateFixed, LockKeyhole, LockOpen,
  Luggage, Magnet, MailCheck, MailMinus, MailOpen, MailPlus, MailQuestion, MailSearch,
  MailWarning, MailX, Map as MapIcon, Medal, Megaphone as MegaphoneIcon, MemoryStick,
  MenuSquare, Merge, Microscope, Microwave as MicrowaveIcon, Milestone, Milk, MinusCircle,
  MinusSquare, MonitorCheck, MonitorDot, MonitorOff, MonitorPause, MonitorPlay,
  MonitorSpeaker, MonitorStop, MonitorUp, MonitorX, MoonStar, Mountain, MountainSnow,
  MousePointer2, MousePointerClick, Move3d, MoveDiagonal, MoveDiagonal2, MoveHorizontal,
  MoveVertical, Music2, Music3, Music4, Network as NetworkIcon, Newspaper, Nfc, Nut,
  Option, Orbit, PackageCheck, PackageMinus, PackageOpen, PackagePlus, PackageSearch,
  PackageX, PaintBucket, Paintbrush, Paintbrush2, Palette as PaletteIcon, Palmtree,
  PanelBottom, PanelLeft, PanelRight, PanelTop, Paperclip as PaperclipIcon, Parentheses,
  ParkingSquare, PartyPopper, PauseCircle, PauseOctagon, PawPrint, PcCase, Pen, PenLine,
  Pencil, PencilRuler, Percent, PersonStanding, PhoneCall, PhoneForwarded, PhoneIncoming,
  PhoneMissed, PhoneOff, PhoneOutgoing, Pi, Piano, PictureInPicture, PictureInPicture2,
  PiggyBank, Pilcrow, Pill, Pin, PinOff, Pipette as PipetteIcon, PlaneLanding, PlaneTakeoff,
  PlayCircle, PlaySquare, PlugZap, Pocket, Podcast, Pointer, Popcorn, PoundSterling,
  PowerOff, Presentation, Printer as PrinterIcon, Projector as ProjectorIcon, Puzzle,
  QrCode, Quote, Radar, Radiation, Radio as RadioIcon, RadioReceiver, RailSymbol,
  Rainbow, Rat, Ratio, Receipt, RectangleHorizontal, RectangleVertical, Recycle as RecycleIcon,
  Redo, Redo2, RefreshCcwDot, RefreshCwOff, Regex, Replace, ReplaceAll, Reply, ReplyAll,
  Rewind, Rocket, RockingChair, RollerCoaster, Rotate3d, Router as RouterIcon, Rss,
  Ruler as RulerIcon, RussianRuble, Sailboat, Salad, Sandwich, Satellite, SatelliteDish,
  SaveAll, Scale, Scale3d, Scaling, Scan, ScanBarcode, ScanEye, ScanFace, ScanLine,
  School, Scissors as ScissorsIcon, ScreenShare, ScreenShareOff, Scroll, ScrollText,
  SearchCheck, SearchCode, SearchSlash, SearchX, Send as SendIcon, SeparatorHorizontal,
  SeparatorVertical, Server as ServerIcon, ServerCog, ServerCrash, ServerOff, Settings2,
  Shapes, Share as ShareIcon, Sheet, Shell, ShieldAlert, ShieldBan, ShieldCheck,
  ShieldClose, ShieldOff, ShieldQuestion, Ship, Shirt, Shovel, Shrink, Shuffle as ShuffleIcon,
  Sigma, SignalHigh, SignalLow, SignalMedium, SignalZero, Signpost as SignpostIcon,
  Siren as SirenIcon, Skull, Slack, Slice, Sliders, SlidersHorizontal, SmartphoneCharging,
  SmartphoneNfc, Snowflake, Sofa as SofaIcon, SortAsc, SortDesc, Soup, Space, Spade,
  Sparkle, Sparkles, Speaker as SpeakerIcon, Sprout, Square as SquareIcon, SquareAsterisk,
  SquareCode, SquareDashedBottom, SquareDot, SquareEqual,
  SquareSlash, Stamp as StampIcon, Star as StarIcon, StarHalf, StepBack, StepForward,
  Stethoscope, Sticker, StickyNote, StopCircle as StopCircleIcon, Store, Strikethrough,
  Subscript, Subtitles, SunDim, SunMedium, SunMoon, SunSnow, Sunrise, Sunset, Superscript,
  SwissFranc, SwitchCamera, Sword, Swords, Syringe, Table2, Tablet as TabletIcon,
  TabletSmartphone, Tags, Target as TargetIcon, Tent, TentTree, Terminal as TerminalIcon,
  TerminalSquare, TestTube, TestTube2, Text, TextCursor, TextSelect, Theater, Thermometer as ThermometerIcon,
  ThermometerSnowflake as ThermometerSnowflakeIcon, ThermometerSun as ThermometerSunIcon,
  Ticket, Timer, TimerOff, TimerReset, ToggleLeft as ToggleLeftIcon, ToggleRight as ToggleRightIcon,
  Tornado, Touchpad, TouchpadOff, TowerControl, ToyBrick, Tractor, TrafficCone, TrainFront,
  TrainTrack, TramFront, Trash as TrashIcon, Trash2 as Trash2Icon, TreeDeciduous,
  TreePine as TreePineIcon, Trees, Trello, TrendingDown as TrendingDownIcon, TrendingUp as TrendingUpIcon,
  Triangle, Trophy, Truck as TruckIcon, Tv as TvIcon, Tv2, Twitch, Twitter, Type,
  Umbrella as UmbrellaIcon, Underline, Undo, Undo2, UnfoldHorizontal, UnfoldVertical,
  Unlink, Unlink2, Unlock as UnlockIcon, Upload as UploadIcon, UploadCloud, Usb as UsbIcon,
  UserCheck as UserCheckIcon, UserCog, UserMinus as UserMinusIcon, UserPlus as UserPlusIcon,
  UserX as UserXIcon, Users as UsersIcon, Users2, Utensils as UtensilsIcon, UtilityPole,
  Variable, Vault, Vegan, VenetianMask, Verified, Vibrate, VibrateOff, Video as VideoIcon,
  VideoOff, View, Voicemail as VoicemailIcon, Volume as VolumeIcon, Volume1 as Volume1Icon,
  Volume2 as Volume2Icon, VolumeX as VolumeXIcon, Vote, Wallet, Wallet2, Wallpaper,
  Wand as WandIcon, Wand2, Warehouse, Watch as WatchIcon, Waves as WavesIcon, Webcam,
  Webhook, Wheat, WheatOff, WholeWord, Wifi as WifiIcon, WifiOff as WifiOffIcon, Wind as WindIcon,
  Wine, WineOff, Workflow, WrapText, Wrench as WrenchIcon, X as XIcon, XCircle as XCircleIcon,
  XOctagon, XSquare, Youtube, Zap as ZapIcon, ZapOff, ZoomIn as ZoomInIcon2, ZoomOut as ZoomOutIcon2
} from 'lucide-react';

// Organized Categories for better UX (Future improvement: group in modal)
export const ICON_MAP: Record<string, React.FC<any>> = {
  // --- Common / Construction ---
  'Hoiatus': AlertTriangle,
  'Elekter': Zap,
  'Pistik': Plug,
  'Pistik 2': Plug2,
  'Lüliti': ToggleRight,
  'Lamp': Lamp,
  'Pirn': Lightbulb,
  'Pirn (Väljas)': LightbulbOff,
  'Laevalgusti': LampCeiling,
  'Laualamp': LampDesk,
  'Põrandalamp': LampFloor,
  'Seinalamp': LampWallUp,
  'Server': Server,
  'Võrk': Network,
  'Wifi': Wifi,
  'Ruuter': Router,
  'Signaal': Signal,
  'Kaabel': Cable,
  'Trükkplaat': CircuitBoard,
  'Tulekahju': Flame,
  'Tulekustuti': FireExtinguisher,
  'Suitsuandur': CircleDot, 
  'Vesi': Droplet,
  'Niiskus': Droplets,
  'Termomeeter': Thermometer,
  'Külm': ThermometerSnowflake,
  'Soe': ThermometerSun,
  'Ventilatsioon': Fan,
  'Õhuava': AirVent,
  'Kliima': Wind,
  'Radiaator': Waves,
  'Tellissein': BrickWall,
  'Piire': Fence,
  'Koonus': TrafficCone,
  'Kiiver': HardHat,
  'Redel': StepForward, // Changed from Ladder to StepForward
  
  // --- Furniture & Interior ---
  'Uks (Lahti)': DoorOpen,
  'Uks (Kinni)': DoorClosed,
  'Aken (Ruloo)': Blinds,
  'Voodi': Bed,
  'Voodi (Üksik)': BedSingle,
  'Voodi (Topelt)': BedDouble,
  'Diivan': Sofa,
  'Tugitool': Armchair,
  'Laud': Table,
  'Töölaud': Table2,
  'Kapp': Box,
  'Külmkapp': Refrigerator,
  'Mikrolaineahi': Microwave,
  'Vann': Bath,
  'Dušš': ShowerHead,
  'WC': Recycle,
  'Köök': ChefHat,
  'Söögiriistad': Utensils,
  'Kohv': Coffee,
  'Taim': Sprout,
  'Lill': Flower2,
  'Puu': TreePine,
  'Kardinad': Scroll,
  'Peegel': RectangleVertical, 
  'Kell': Clock,
  'Prügikast': Trash2,

  // --- Tools & Actions ---
  'Mõõda': Ruler,
  'Haamer': Hammer,
  'Trell': Drill,
  'Mutrivõti': Wrench,
  'Kruvikeeraja': PenTool, 
  'Kirves': Axe,
  'Labidas': Shovel,
  'Ehitus': Construction,
  'Lõika': Scissors,
  'Kleebi': Clipboard,
  'Pintsel': Brush,
  'Rull': Brush, // Changed from PaintRoller to Brush
  'Värvipott': PaintBucket,
  'Pliiats': Pen,
  'Joonlaud': RulerIcon,
  'Kustukumm': Eraser,
  'Lukk (Kinni)': Lock,
  'Lukk (Lahti)': Unlock,
  'Võti': Key,
  'Seaded': Settings,
  'Seaded 2': Settings2,

  // --- Directions & Arrows ---
  'Nool Üles': ArrowUpCircle,
  'Nool Alla': ArrowDownCircle,
  'Nool Vasakule': ArrowLeftCircle, 
  'Nool Paremale': ArrowRightCircle,
  'Suur Nool Üles': ArrowBigUp,
  'Suur Nool Alla': ArrowBigDown,
  'Suur Nool Vasak': ArrowBigLeft,
  'Suur Nool Parem': ArrowBigRight,
  'Pööra Vasak': CornerDownLeft,
  'Pööra Parem': CornerDownRight,
  'Tagasipööre': Undo2,
  'Edasipööre': Redo2,
  'Laienda': Maximize,
  'Vähenda': Minimize,
  'Liiguta': Move,
  
  // --- Technology & Devices ---
  'Arvuti': Monitor,
  'Sülearvuti': Laptop,
  'Telefon': Smartphone,
  'Tahvel': Tablet,
  'Klaviatuur': Keyboard,
  'Hiir': Mouse,
  'Printer': Printer,
  'Projektor': Projector,
  'Kaamera': Camera,
  'Videokaamera': Video,
  'CCTV': Cctv,
  'Mikrofon': Mic,
  'Kõlar': Speaker,
  'Kõrvaklapid': Headphones,
  'USB': Usb,
  'Aku': Battery,
  'Andmebaas': Database,
  'Protsessor': Cpu,
  'Mälupulk': MemoryStick,
  'Kell (Nutikas)': Watch,
  'Pult': Gamepad2,

  // --- Maps & Outdoors ---
  'Kaart': Map,
  'Asukoht': MapPin,
  'Kompass': Compass,
  'Gloobus': Globe,
  'Maja': Home,
  'Hoone': Building,
  'Kõrghoone': Building2,
  'Vabrik': Factory,
  'Ladu': Warehouse,
  'Telk': Tent,
  'Mägi': Mountain,
  'Parkla': ParkingCircle,
  'Auto': Car,
  'Auto (Eest)': CarFront,
  'Veok': Truck,
  'Buss': Bus,
  'Rong': Train,
  'Lennuk': Plane,
  'Laev': Ship,
  'Jalgratas': Bike,
  'Traktor': Tractor,
  'Tõstuk': Forklift,
  'Silt': Signpost,
  'Valgusfoor': Siren, 

  // --- Medical & Safety ---
  'Esmaabi': Cross, 
  'Süda': Heart,
  'Kiirabi': Siren,
  'Haigla': Activity,
  'Tablett': Pill,
  'Süstal': Syringe,
  'Biooht': Biohazard,
  'Kiiritus': Radiation,
  'DNA': Dna,
  'Stetoskoop': Stethoscope,
  'Ratastool': Accessibility,
  
  // --- Shapes & Geometry ---
  'Ruut': Square,
  'Ring': Circle, 
  'Kolmnurk': Triangle,
  'Hulknurk': Hexagon,
  'Täht': Star,
  'Kuup': Box,
  'Silinder': Cylinder,
  'Koonus (Geom)': Triangle, // Changed from Cone to Triangle
  
  // --- Misc & Symbols ---
  'Info': Info,
  'Küsimus': HelpCircle,
  'Hoiatusmärk': AlertTriangle,
  'Kinnitatud': CheckCircle,
  'Viga': XCircle,
  'Keelatud': XCircle, // Changed from Ban to XCircle
  'Lemmik': Star,
  'Lipp': Flag,
  'Silt (Tag)': Tag,
  'Järjehoidja': Bookmark,
  'Link': Link,
  'Klamber': Paperclip,
  'Kalender': Calendar,
  'Kell (Aeg)': Clock,
  'Stopper': Timer,
  'Raha': DollarSign,
  'Euro': Euro,
  'Ostukorv': ShoppingCart,
  'Kink': Gift,
  'Muusika': Music,
  'Pilt': Image,
  'Video': Film,
  'Dokument': FileText,
  'Kaust': Folder,
  'Arhiiv': Archive,
  'Post': Mail,
  'Inimene': User,
  'Grupp': Users,
  'ID Kaart': Contact,
  'Sõrmejälg': Fingerprint,
  'Koer': Dog,
  'Kass': Cat,
  'Kala': Fish,
  'Lind': Feather, // Changed from Bird to Feather
  'Päike': Sun,
  'Kuu': Moon,
  'Pilv': Cloud,
  'Vihm': CloudRain,
  'Lumi': CloudSnow,
  'Äike': CloudLightning,
  'Vikerkaar': Rainbow,
  'Naeratus': Smile,
  'Kurb': Frown,
  'Kummitus': Ghost,
  'Kolju': Skull,
  'Teemant': Diamond,
  'Kroon': Crown,
  'Auhind': Trophy,
  'Medal': Medal,
  'Sihtmärk': Target
};

function ArrowLeftCircle(props: any) { return React.createElement(ArrowDownCircle, { ...props, style: { transform: 'rotate(90deg)' } }); } 
function ArrowRightCircle(props: any) { return React.createElement(ArrowDownCircle, { ...props, style: { transform: 'rotate(-90deg)' } }); }

export const getIconComponent = (name: string) => {
  return ICON_MAP[name] || Zap;
};